package actions

import (
	"github.com/ECAllen/debatehub/models"
	"github.com/gobuffalo/buffalo"
	"github.com/markbates/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Debate2thread)
// DB Table: Plural (debate2threads)
// Resource: Plural (Debate2threads)
// Path: Plural (/debate2threads)
// View Template Folder: Plural (/templates/debate2threads/)

// Debate2threadsResource is the resource for the debate2thread model
type Debate2threadsResource struct {
	buffalo.Resource
}

// List gets all Debate2threads. This function is mapped to the path
// GET /debate2threads
func (v Debate2threadsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	debate2threads := &models.Debate2threads{}
	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())
	// You can order your list here. Just change
	err := q.All(debate2threads)
	// to:
	// err := q.Order("created_at desc").All(debate2threads)
	if err != nil {
		return errors.WithStack(err)
	}
	// Make Debate2threads available inside the html template
	c.Set("debate2threads", debate2threads)
	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)
	return c.Render(200, r.HTML("debate2threads/index.html"))
}

// Show gets the data for one Debate2thread. This function is mapped to
// the path GET /debate2threads/{debate2thread_id}
func (v Debate2threadsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Debate2thread
	debate2thread := &models.Debate2thread{}
	// To find the Debate2thread the parameter debate2thread_id is used.
	err := tx.Find(debate2thread, c.Param("debate2thread_id"))
	if err != nil {
		return errors.WithStack(err)
	}
	// Make debate2thread available inside the html template
	c.Set("debate2thread", debate2thread)
	return c.Render(200, r.HTML("debate2threads/show.html"))
}

// New renders the form for creating a new Debate2thread.
// This function is mapped to the path GET /debate2threads/new
func (v Debate2threadsResource) New(c buffalo.Context) error {
	// Make debate2thread available inside the html template
	c.Set("debate2thread", &models.Debate2thread{})
	return c.Render(200, r.HTML("debate2threads/new.html"))
}

// Create adds a Debate2thread to the DB. This function is mapped to the
// path POST /debate2threads
func (v Debate2threadsResource) Create(c buffalo.Context) error {
	// Allocate an empty Debate2thread
	debate2thread := &models.Debate2thread{}
	// Bind debate2thread to the html form elements
	err := c.Bind(debate2thread)
	if err != nil {
		return errors.WithStack(err)
	}
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(debate2thread)
	if err != nil {
		return errors.WithStack(err)
	}
	if verrs.HasAny() {
		// Make debate2thread available inside the html template
		c.Set("debate2thread", debate2thread)
		// Make the errors available inside the html template
		c.Set("errors", verrs)
		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.HTML("debate2threads/new.html"))
	}
	// If there are no errors set a success message
	c.Flash().Add("success", "Debate2thread was created successfully")
	// and redirect to the debate2threads index page
	return c.Redirect(302, "/debate2threads/%s", debate2thread.ID)
}

// Edit renders a edit form for a debate2thread. This function is
// mapped to the path GET /debate2threads/{debate2thread_id}/edit
func (v Debate2threadsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Debate2thread
	debate2thread := &models.Debate2thread{}
	err := tx.Find(debate2thread, c.Param("debate2thread_id"))
	if err != nil {
		return errors.WithStack(err)
	}
	// Make debate2thread available inside the html template
	c.Set("debate2thread", debate2thread)
	return c.Render(200, r.HTML("debate2threads/edit.html"))
}

// Update changes a debate2thread in the DB. This function is mapped to
// the path PUT /debate2threads/{debate2thread_id}
func (v Debate2threadsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Debate2thread
	debate2thread := &models.Debate2thread{}
	err := tx.Find(debate2thread, c.Param("debate2thread_id"))
	if err != nil {
		return errors.WithStack(err)
	}
	// Bind Debate2thread to the html form elements
	err = c.Bind(debate2thread)
	if err != nil {
		return errors.WithStack(err)
	}
	verrs, err := tx.ValidateAndUpdate(debate2thread)
	if err != nil {
		return errors.WithStack(err)
	}
	if verrs.HasAny() {
		// Make debate2thread available inside the html template
		c.Set("debate2thread", debate2thread)
		// Make the errors available inside the html template
		c.Set("errors", verrs)
		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.HTML("debate2threads/edit.html"))
	}
	// If there are no errors set a success message
	c.Flash().Add("success", "Debate2thread was updated successfully")
	// and redirect to the debate2threads index page
	return c.Redirect(302, "/debate2threads/%s", debate2thread.ID)
}

// Destroy deletes a debate2thread from the DB. This function is mapped
// to the path DELETE /debate2threads/{debate2thread_id}
func (v Debate2threadsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Debate2thread
	debate2thread := &models.Debate2thread{}
	// To find the Debate2thread the parameter debate2thread_id is used.
	err := tx.Find(debate2thread, c.Param("debate2thread_id"))
	if err != nil {
		return errors.WithStack(err)
	}
	err = tx.Destroy(debate2thread)
	if err != nil {
		return errors.WithStack(err)
	}
	// If there are no errors set a flash message
	c.Flash().Add("success", "Debate2thread was destroyed successfully")
	// Redirect to the debate2threads index page
	return c.Redirect(302, "/debate2threads")
}
