package actions

import (
	"github.com/ECAllen/debatehub/models"
	"github.com/gobuffalo/buffalo"
	"github.com/markbates/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Hashtag)
// DB Table: Plural (hashtags)
// Resource: Plural (Hashtags)
// Path: Plural (/hashtags)
// View Template Folder: Plural (/templates/hashtags/)

// HashtagsResource is the resource for the hashtag model
type HashtagsResource struct {
	buffalo.Resource
}

// List gets all Hashtags. This function is mapped to the path
// GET /hashtags
func (v HashtagsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	hashtags := &models.Hashtags{}
	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())
	// You can order your list here. Just change
	err := q.All(hashtags)
	// to:
	// err := q.Order("created_at desc").All(hashtags)
	if err != nil {
		return errors.WithStack(err)
	}
	// Make Hashtags available inside the html template
	c.Set("hashtags", hashtags)
	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)
	return c.Render(200, r.HTML("hashtags/index.html"))
}

// Show gets the data for one Hashtag. This function is mapped to
// the path GET /hashtags/{hashtag_id}
func (v HashtagsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Hashtag
	hashtag := &models.Hashtag{}
	// To find the Hashtag the parameter hashtag_id is used.
	err := tx.Find(hashtag, c.Param("hashtag_id"))
	if err != nil {
		return errors.WithStack(err)
	}
	// Make hashtag available inside the html template
	c.Set("hashtag", hashtag)
	return c.Render(200, r.HTML("hashtags/show.html"))
}

// New renders the form for creating a new Hashtag.
// This function is mapped to the path GET /hashtags/new
func (v HashtagsResource) New(c buffalo.Context) error {
	// Make hashtag available inside the html template
	c.Set("hashtag", &models.Hashtag{})
	return c.Render(200, r.HTML("hashtags/new.html"))
}

// Create adds a Hashtag to the DB. This function is mapped to the
// path POST /hashtags
func (v HashtagsResource) Create(c buffalo.Context) error {
	// Allocate an empty Hashtag
	hashtag := &models.Hashtag{}
	// Bind hashtag to the html form elements
	err := c.Bind(hashtag)
	if err != nil {
		return errors.WithStack(err)
	}
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(hashtag)
	if err != nil {
		return errors.WithStack(err)
	}
	if verrs.HasAny() {
		// Make hashtag available inside the html template
		c.Set("hashtag", hashtag)
		// Make the errors available inside the html template
		c.Set("errors", verrs)
		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.HTML("hashtags/new.html"))
	}
	// If there are no errors set a success message
	c.Flash().Add("success", "Hashtag was created successfully")
	// and redirect to the hashtags index page
	return c.Redirect(302, "/hashtags/%s", hashtag.ID)
}

// Edit renders a edit form for a hashtag. This function is
// mapped to the path GET /hashtags/{hashtag_id}/edit
func (v HashtagsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Hashtag
	hashtag := &models.Hashtag{}
	err := tx.Find(hashtag, c.Param("hashtag_id"))
	if err != nil {
		return errors.WithStack(err)
	}
	// Make hashtag available inside the html template
	c.Set("hashtag", hashtag)
	return c.Render(200, r.HTML("hashtags/edit.html"))
}

// Update changes a hashtag in the DB. This function is mapped to
// the path PUT /hashtags/{hashtag_id}
func (v HashtagsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Hashtag
	hashtag := &models.Hashtag{}
	err := tx.Find(hashtag, c.Param("hashtag_id"))
	if err != nil {
		return errors.WithStack(err)
	}
	// Bind Hashtag to the html form elements
	err = c.Bind(hashtag)
	if err != nil {
		return errors.WithStack(err)
	}
	verrs, err := tx.ValidateAndUpdate(hashtag)
	if err != nil {
		return errors.WithStack(err)
	}
	if verrs.HasAny() {
		// Make hashtag available inside the html template
		c.Set("hashtag", hashtag)
		// Make the errors available inside the html template
		c.Set("errors", verrs)
		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.HTML("hashtags/edit.html"))
	}
	// If there are no errors set a success message
	c.Flash().Add("success", "Hashtag was updated successfully")
	// and redirect to the hashtags index page
	return c.Redirect(302, "/hashtags/%s", hashtag.ID)
}

// Destroy deletes a hashtag from the DB. This function is mapped
// to the path DELETE /hashtags/{hashtag_id}
func (v HashtagsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Hashtag
	hashtag := &models.Hashtag{}
	// To find the Hashtag the parameter hashtag_id is used.
	err := tx.Find(hashtag, c.Param("hashtag_id"))
	if err != nil {
		return errors.WithStack(err)
	}
	err = tx.Destroy(hashtag)
	if err != nil {
		return errors.WithStack(err)
	}
	// If there are no errors set a flash message
	c.Flash().Add("success", "Hashtag was destroyed successfully")
	// Redirect to the hashtags index page
	return c.Redirect(302, "/hashtags")
}
