package actions

import (
	"github.com/ECAllen/debatehub/models"
	"github.com/gobuffalo/buffalo"
	"github.com/markbates/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Profiles2debate)
// DB Table: Plural (profiles2debates)
// Resource: Plural (Profiles2debates)
// Path: Plural (/profiles2debates)
// View Template Folder: Plural (/templates/profiles2debates/)

// Profiles2debatesResource is the resource for the profiles2debate model
type Profiles2debatesResource struct {
	buffalo.Resource
}

// List gets all Profiles2debates. This function is mapped to the path
// GET /profiles2debates
func (v Profiles2debatesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	profiles2debates := &models.Profiles2debates{}
	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())
	// You can order your list here. Just change
	err := q.All(profiles2debates)
	// to:
	// err := q.Order("created_at desc").All(profiles2debates)
	if err != nil {
		return errors.WithStack(err)
	}
	// Make Profiles2debates available inside the html template
	c.Set("profiles2debates", profiles2debates)
	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)
	return c.Render(200, r.HTML("profiles2debates/index.html"))
}

// Show gets the data for one Profiles2debate. This function is mapped to
// the path GET /profiles2debates/{profiles2debate_id}
func (v Profiles2debatesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Profiles2debate
	profiles2debate := &models.Profiles2debate{}
	// To find the Profiles2debate the parameter profiles2debate_id is used.
	err := tx.Find(profiles2debate, c.Param("profiles2debate_id"))
	if err != nil {
		return errors.WithStack(err)
	}
	// Make profiles2debate available inside the html template
	c.Set("profiles2debate", profiles2debate)
	return c.Render(200, r.HTML("profiles2debates/show.html"))
}

// New renders the form for creating a new Profiles2debate.
// This function is mapped to the path GET /profiles2debates/new
func (v Profiles2debatesResource) New(c buffalo.Context) error {
	// Make profiles2debate available inside the html template
	c.Set("profiles2debate", &models.Profiles2debate{})
	return c.Render(200, r.HTML("profiles2debates/new.html"))
}

// Create adds a Profiles2debate to the DB. This function is mapped to the
// path POST /profiles2debates
func (v Profiles2debatesResource) Create(c buffalo.Context) error {
	// Allocate an empty Profiles2debate
	profiles2debate := &models.Profiles2debate{}
	// Bind profiles2debate to the html form elements
	err := c.Bind(profiles2debate)
	if err != nil {
		return errors.WithStack(err)
	}
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(profiles2debate)
	if err != nil {
		return errors.WithStack(err)
	}
	if verrs.HasAny() {
		// Make profiles2debate available inside the html template
		c.Set("profiles2debate", profiles2debate)
		// Make the errors available inside the html template
		c.Set("errors", verrs)
		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.HTML("profiles2debates/new.html"))
	}
	// If there are no errors set a success message
	c.Flash().Add("success", "Profiles2debate was created successfully")
	// and redirect to the profiles2debates index page
	return c.Redirect(302, "/profiles2debates/%s", profiles2debate.ID)
}

// Edit renders a edit form for a profiles2debate. This function is
// mapped to the path GET /profiles2debates/{profiles2debate_id}/edit
func (v Profiles2debatesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Profiles2debate
	profiles2debate := &models.Profiles2debate{}
	err := tx.Find(profiles2debate, c.Param("profiles2debate_id"))
	if err != nil {
		return errors.WithStack(err)
	}
	// Make profiles2debate available inside the html template
	c.Set("profiles2debate", profiles2debate)
	return c.Render(200, r.HTML("profiles2debates/edit.html"))
}

// Update changes a profiles2debate in the DB. This function is mapped to
// the path PUT /profiles2debates/{profiles2debate_id}
func (v Profiles2debatesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Profiles2debate
	profiles2debate := &models.Profiles2debate{}
	err := tx.Find(profiles2debate, c.Param("profiles2debate_id"))
	if err != nil {
		return errors.WithStack(err)
	}
	// Bind Profiles2debate to the html form elements
	err = c.Bind(profiles2debate)
	if err != nil {
		return errors.WithStack(err)
	}
	verrs, err := tx.ValidateAndUpdate(profiles2debate)
	if err != nil {
		return errors.WithStack(err)
	}
	if verrs.HasAny() {
		// Make profiles2debate available inside the html template
		c.Set("profiles2debate", profiles2debate)
		// Make the errors available inside the html template
		c.Set("errors", verrs)
		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.HTML("profiles2debates/edit.html"))
	}
	// If there are no errors set a success message
	c.Flash().Add("success", "Profiles2debate was updated successfully")
	// and redirect to the profiles2debates index page
	return c.Redirect(302, "/profiles2debates/%s", profiles2debate.ID)
}

// Destroy deletes a profiles2debate from the DB. This function is mapped
// to the path DELETE /profiles2debates/{profiles2debate_id}
func (v Profiles2debatesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)
	// Allocate an empty Profiles2debate
	profiles2debate := &models.Profiles2debate{}
	// To find the Profiles2debate the parameter profiles2debate_id is used.
	err := tx.Find(profiles2debate, c.Param("profiles2debate_id"))
	if err != nil {
		return errors.WithStack(err)
	}
	err = tx.Destroy(profiles2debate)
	if err != nil {
		return errors.WithStack(err)
	}
	// If there are no errors set a flash message
	c.Flash().Add("success", "Profiles2debate was destroyed successfully")
	// Redirect to the profiles2debates index page
	return c.Redirect(302, "/profiles2debates")
}
